[package]
name = "opencvtest"
version = "0.1.0"
authors = ["Orest Dubay <orest3.dubay@gmail.com>"]
edition = "2018"

[dependencies]
opencv = {version = "0.19", default-features = false, features = ["opencv-32"]}